import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Resume Analyzer",
  keywords: ["Resume", "Analyzer", "AI", "Chatbot"],
  authors: [{ name: "Rupesh Rajhans", url: "https://github.com/rupeshrajhans" }],
  creator: "Rupesh Rajhans",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
